### ISSUE TITLE
Add count meta to all collection relationships

### ISSUE THREAD

**Issue by ezekg** [keygen-sh/keygen-api#106]
This will allow accounts to more easily track limits associated with their plan, as well as track limits associated with their users e.g. their machine count.

**Comment by ArlonSwaders** [comment]
@ezekg It would be great if another attempt could be made to add the counters.

Use Case: I would like to provide my clients statistics about the total number of licenses, machines, and users they have for a product.

Currently, achieving this seems very convoluted, due to the pagination in the API. It would be great to at least have the API provide the total counts.

Happy to hear your thoughts.

**Comment by ezekg** [comment]
@ArlonSwaders you can already use filters and pagination for this. When paginating, if you look at `links.meta.count`, you'll find the total resource count according to any filters you're using. E.g. add all client resources to a group and do:

```diff
GET /v1/accounts/<account>/licenses?page[size]=25&page[number]=1&group=<group>
{
  "data": [
    ...
  ],
  "links": {
    "self": "/v1/accounts/<account>/licenses?page[size]=25&page[number]=2&group=<group>",
    "prev": "/v1/accounts/<account>/licenses?page[size]=25&page[number]=1&group=<group>",
    "next": "/v1/accounts/<account>/licenses?page[size]=25&page[number]=3&group=<group>",
    "first": "/v1/accounts/<account>/licenses?page[size]=25&page[number]=1&group=<group>",
    "last": "/v1/accounts/<account>/licenses?page[size]=25&page[number]=4&group=<group>",
    "meta": {
      "pages": 4,
+     "count": 98
    }
  }
}
```

For performance reasons, I don't see us revisiting this issue anytime soon.
