### ISSUE TITLE
Email whitelisting and blacklisting

### ISSUE THREAD

**Issue by ayntk-ai** [keygen-sh/keygen-api#785]
Please add the following features to Keygen:

- [ ] Whitelist a specific email address.
- [ ] Whitelist a specific domain so that all email addresses in that domain/subdomain are allowed, but only those addresses -> wildcard domain whitelisting.
- [ ] Blacklist just one email address from using the license key
- [ ] Blacklist whole domains using wildcards

**Comment by ezekg** [comment]
What's your use case for this? Can you elaborate? With multi-user licensing coming in #774, you will be able to set up multi-user licenses, so I'm unsure of how an email whitelist feature would be beneficial or unsure how that would work i.r.t. e.g. validation.

**Comment by ayntk-ai** [comment]
With multi-keys I want to be able to prevent users from using the key, e.g. if the key is shared. 
Also the key is only allowed for all people in an organization -> all people in this organization have a company email and to prevent license key sharing the license key is only seen as valid if a user has a key + the key multi-user limit is still below the max and the email domain is the one from the company.

**Comment by ezekg** [comment]
I think this will be handled in #774. I don't think introducing email "whitelisting" makes a lot of sense in terms of functionality when multi-user licenses will handle this already (by creating a user for each email and attaching each user to a license). A whitelisting approach would essentially be the same thing, since user objects only require an email (i.e. password and name are optional), effectively whitelisting it. Groups can then be used to add a max user limit to a license.
