### ISSUE TITLE
Allow calling APIs with `/account/<acount_id>/` in the singleplayer mode

### ISSUE THREAD

**Issue by aminya** [keygen-sh/keygen-api#812]
The documentation of the singleplayer mode specifies that the `/account/<account_id>/` prefix "can" be removed, meaning it is optional, and it can be also provided. However, based on my tests, if the account id is provided, the server returns `404`, and the prefix "must" be removed.

I am working on a Rust SDK for keygen-api, and this difference makes creating the SDK more complex. Could you make it possible to also provide the account_id in the singleplayer mode, so that the SDKs for both modes can use the same APIs and codebase without needing special conditions?

**Comment by ezekg** [comment]
This is already supported. If you're receiving a 404, it's because your `KEYGEN_HOST` environment variable is not configured correctly, so the router fails to route to routes with the `/accounts` prefix. It should be set to the full domain you're hosting Keygen at, e.g. `licensing.example.com`. Please refer to the docs on required configuration: https://keygen.sh/docs/self-hosting/#configuration

**Comment by aminya** [comment]
My keygen host is correctly set, and I can confirm it either by one of these two in Postman
- `{{baseUrl}}/ping`: returns the ping headers correctly
- `{{baseUrl}}/tokens`: that correctly generates a token.

However, when I try `{{baseUrl}}/accounts/:account/tokens`, it doesn't work.
I use the same account id I set in `KEYGEN_ACCOUNT_ID`.

**Comment by aminya** [comment]
Okay, I found the issue. In the development mode, the sub has to be explicitly set to  `api`. 
Meaning the host should be something like `api.example.com`. Any other format would not work because of this check

https://github.com/keygen-sh/keygen-api/blob/c73f7b01239d19064bef19f32b4dda04398e1eb7/config/routes.rb#L24-L39

**Comment by ezekg** [comment]
Ah, okay. Why are you running Keygen CE in development mode?
